vim.keymap.set("n", "<leader>ct", "<cmd>lua require('crates').toggle()<CR>", { desc = "Toggle crates", buffer = true })
vim.keymap.set("n", "<leader>cr", "<cmd>lua require('crates').reload()<CR>", { desc = "Reload crates", buffer = true })
vim.keymap.set("n", "<leader>cv", "<cmd>lua require('crates').show_versions_popup()<CR>", { desc = "Show crates versions", buffer = true })
vim.keymap.set("n", "<leader>cf", "<cmd>lua require('crates').show_features_popup()<CR>", { desc = "Show crates features", buffer = true })
vim.keymap.set("n", "<leader>cd", "<cmd>lua require('crates').show_dependencies_popup()<CR>", { desc = "Show crates dependencies", buffer = true })
vim.keymap.set("n", "<leader>cu", "<cmd>lua require('crates').update_crate()<CR>", { desc = "Update crates", buffer = true })
vim.keymap.set("n", "<leader>cU", "<cmd>lua require('crates').upgrade_crate()<CR>", { desc = "Upgrade crates", buffer = true })
vim.keymap.set("n", "<leader>ca", "<cmd>lua require('crates').update_all_crates()<CR>", { desc = "Update all crates", buffer = true })
vim.keymap.set("n", "<leader>cA", "<cmd>lua require('crates').upgrade_all_crates()<CR>", { desc = "Upgrade all crates", buffer = true })
vim.keymap.set("n", "<leader>ck", "<cmd>lua require('user.utils.crates').show_documentation()<CR>", { desc = "Show crate docs", buffer = true })
vim.keymap.set("n", "<leader>ch", "<cmd>lua require('crates').open_homepage()<CR>", { desc = "Open crates homepage", buffer = true })
vim.keymap.set("n", "<leader>cR", "<cmd>lua require('crates').open_repository()<CR>", { desc = "Open crates repo", buffer = true })
vim.keymap.set("n", "<leader>cD", "<cmd>lua require('crates').open_documentation()<CR>", { desc = "Open crates docs", buffer = true })
