vim.keymap.set("n", "<leader>rct", "<cmd>lua require('crates').toggle()<CR>", { desc = "Toggle crates", buffer = true })
vim.keymap.set("n", "<leader>rcr", "<cmd>lua require('crates').reload()<CR>", { desc = "Reload crates", buffer = true })
vim.keymap.set("n", "<leader>rcv", "<cmd>lua require('crates').show_versions_popup()<CR>", { desc = "Show crates versions", buffer = true })
vim.keymap.set("n", "<leader>rcf", "<cmd>lua require('crates').show_features_popup()<CR>", { desc = "Show crates features", buffer = true })
vim.keymap.set("n", "<leader>rcd", "<cmd>lua require('crates').show_dependencies_popup()<CR>", { desc = "Show crates dependencies", buffer = true })
vim.keymap.set("n", "<leader>rcu", "<cmd>lua require('crates').update_crate()<CR>", { desc = "Update crates", buffer = true })
vim.keymap.set("n", "<leader>rcU", "<cmd>lua require('crates').upgrade_crate()<CR>", { desc = "Upgrade crates", buffer = true })
vim.keymap.set("n", "<leader>rca", "<cmd>lua require('crates').update_all_crates()<CR>", { desc = "Update all crates", buffer = true })
vim.keymap.set("n", "<leader>rcA", "<cmd>lua require('crates').upgrade_all_crates()<CR>", { desc = "Upgrade all crates", buffer = true })
vim.keymap.set("n", "<leader>rch", "<cmd>lua require('crates').open_homepage()<CR>", { desc = "Open crates homepage", buffer = true })
vim.keymap.set("n", "<leader>rcR", "<cmd>lua require('crates').open_repository()<CR>", { desc = "Open crates repo", buffer = true })
vim.keymap.set("n", "<leader>rcD", "<cmd>lua require('crates').open_documentation()<CR>", { desc = "Open crates docs", buffer = true })
